#!/bin/bash

NAME=$1

zip -r $NAME.love .
unzip ../love_release_cache/love-0.9.1-macosx-x64.zip -d love_mac
cp $NAME.love love_mac/love.app/Contents/Resources
mv love_mac/love.app $NAME.app
zip $NAME.mac.zip -r $NAME.app
rm -rf love_mac
rm -rf $NAME.app

unzip ../love_release_cache/love-0.9.1-win32.zip -d $NAME
mv $NAME/* $NAME/love
mv $NAME/love/* $NAME
rmdir $NAME/love
cat $NAME/love.exe $NAME.love > $NAME/$NAME.exe
rm $NAME/love.exe
zip $NAME.win.zip -r $NAME
rm -rf $NAME
